function plot_hexarotor_geometry(x,y,c_tau_i,bA,best_s,R,fontSize)

if nargin < 7
    fontSize = 30;
end

N = numel(x);

figure('Color','w','Position',[100 100 1100 1000]);
ax = axes;
hold(ax,'on'); grid(ax,'on'); box(ax,'on'); axis(ax,'equal');

set(ax, ...
    'FontName','Helvetica', ...
    'FontSize',fontSize, ...
    'LineWidth',1.2, ...
    'TickLabelInterpreter','latex');

xlabel(ax,'$x$','Interpreter','latex','FontSize',fontSize);
ylabel(ax,'$y$','Interpreter','latex','FontSize',fontSize);

%% Body center
plot(ax,0,0,'ko','MarkerFaceColor','k','MarkerSize',10);

%% Hexarotor frame
theta_circle = linspace(0,2*pi,300);
plot(ax,R*cos(theta_circle),R*sin(theta_circle),'k--','LineWidth',1.2);

%% Arms and propellers
for i = 1:N
    plot(ax,[0 x(i)],[0 y(i)],'k-','LineWidth',2.0);

    if c_tau_i(i) > 0
        markerStyle = '^';
        spinLabel = '$+$';
    else
        markerStyle = 'v';
        spinLabel = '$-$';
    end

    plot(ax,x(i),y(i),markerStyle, ...
        'MarkerSize',18, ...
        'MarkerFaceColor',[0.85 0.85 0.85], ...
        'MarkerEdgeColor','k', ...
        'LineWidth',1.5);

    text(ax,1.13*x(i),1.13*y(i),sprintf('$%d$',i), ...
        'Interpreter','latex', ...
        'FontSize',fontSize, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle');

    text(ax,0.82*x(i),0.82*y(i),spinLabel, ...
        'Interpreter','latex', ...
        'FontSize',round(0.8*fontSize), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle');
end

%% Visualize bA signs around propellers
for i = 1:N
    if bA(i) >= 0
        col = [0.10 0.10 0.10];
        txt = '$b_i^A>0$';
    else
        col = [0.65 0.65 0.65];
        txt = '$b_i^A<0$';
    end

    plot(ax,1.32*x(i),1.32*y(i),'o', ...
        'MarkerSize',13, ...
        'MarkerFaceColor',col, ...
        'MarkerEdgeColor','k');

    text(ax,1.48*x(i),1.48*y(i),txt, ...
        'Interpreter','latex', ...
        'FontSize',round(0.55*fontSize), ...
        'HorizontalAlignment','center');
end

%% Show selected orthant signature best_s
for i = 1:N
    if best_s(i) > 0
        sigText = '$+$';
    else
        sigText = '$-$';
    end

    text(ax,1.70*x(i),1.70*y(i),sigText, ...
        'Interpreter','latex', ...
        'FontSize',round(0.75*fontSize), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle');
end

%% Axes limits
lim = 1.9*R;
xlim(ax,[-lim lim]);
ylim(ax,[-lim lim]);

%% Legend handles
hArm = plot(ax,nan,nan,'k-','LineWidth',2.0);
hCW  = plot(ax,nan,nan,'^','MarkerSize',16,'MarkerFaceColor',[0.85 0.85 0.85], ...
    'MarkerEdgeColor','k','LineWidth',1.5);
hCCW = plot(ax,nan,nan,'v','MarkerSize',16,'MarkerFaceColor',[0.85 0.85 0.85], ...
    'MarkerEdgeColor','k','LineWidth',1.5);
hBp  = plot(ax,nan,nan,'o','MarkerSize',13,'MarkerFaceColor',[0.10 0.10 0.10], ...
    'MarkerEdgeColor','k');
hBm  = plot(ax,nan,nan,'o','MarkerSize',13,'MarkerFaceColor',[0.65 0.65 0.65], ...
    'MarkerEdgeColor','k');

legend(ax,[hArm hCW hCCW hBp hBm], ...
    {'$\mathrm{arm}$', ...
     '$c_{\tau,i}>0$', ...
     '$c_{\tau,i}<0$', ...
     '$b_i^A>0$', ...
     '$b_i^A<0$'}, ...
    'Interpreter','latex', ...
    'FontSize',round(0.65*fontSize), ...
    'Location','southoutside', ...
    'Orientation','horizontal', ...
    'Box','on');

end